baseurl = "http://pr8kerl.github.io/"
languageCode = "en-us"
title = "Curriculum Vitae - Ian Stahnke"
theme = "cv"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
